### PR TITLE
Initial check in with the ranking plot.

### LINKED ISSUE #3: IA2: Ranking chart
Bottom right plot

### PR DESCRIPTION
**Pull request by stevenleung2018**

### CODE REVIEW

**Review by shivajena — CHANGES_REQUESTED** [review]
Tested and works. Two suggestions here, 
1. if you could keep all the data wrangling and other backend codes inside your function, it would be smooth to merge into others' codes.
2. It would be a good idea if we keep app.R separate to avoid merge conflicts and submit individual assignment files separately.

**Comment by stevenleung2018** [comment]
On point 2 above, do you mean you want the file to have a different filename?

**Comment by stevenleung2018** [comment]
For point 1, I will do that but only by later tonight (Wednesday).

**Comment by shivajena** [comment]
> On point 2 above, do you mean you want the file to have a different filename?

Yes @stevenleung2018 , different filename would be convenient and the app.R can be the final one after testing thoroughly.

**Comment by stevenleung2018** [comment]
@shivajena 
1. I have renamed the files.
2. I have moved the code into a function call and tested it locally.

**Comment by shivajena** [comment]
Thanks steven. I will test and merge soon

**Comment by stevenleung2018** [comment]
Changes made to the other branch.  I'm closing this PR.

**Pull request closed without merging**
