### PR TITLE
Feat frontend dash r implementation

### PR DESCRIPTION
**Pull request by shivajena**

### CODE REVIEW

**Comment by shivajena** [comment]
Dashboard completed except for ranking plot. Attached screenshot below
Screenshot 2022-03-16 at 4 17 12 PM
:

**Comment by stevenleung2018** [comment]
@shivajena Have you tried to fix these errors? 
Screen Shot 2022-03-16 at 18 54 44

**Comment by stevenleung2018** [comment]
@shivajena I need to go out to before our call at 21:00.  This is how much I have done.  I have changed the code related to the ranking plot so that it gets the input from the widgets for the ranking plot.  I rename it to a separate file `app_steven.R` under this same branch.  But I still could not get plot to show on the dashboard.  We probably need some other help to troubleshoot it.

**Review by stevenleung2018 — COMMENTED** [review]
I have made changes to the code related to ranking plot as stated in the other comment.

**Comment by stevenleung2018** [comment]
@squisty I notice that when you merge the tables, 2 columns are now created, namely `Breed.x` and `Breed.y` because R does not merge the columns when they are not the key ("BreedID") in this case.  For quick fix would be to mutate one of them to `Breed` and delete the other one.

**Comment by stevenleung2018** [comment]
Screen Shot 2022-03-16 at 20 30 25

**Comment by shivajena** [comment]
All issues resolved now and ready to merge

Screenshot 2022-03-17 at 12 02 55 AM

**Comment by shivajena** [comment]
All issues resolved now and ready to merge

Screenshot 2022-03-17 at 12 02 55 AM

**Pull request merged**
